# Generated by Django 5.2.11 on 2026-03-15 17:41

from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='User',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('username', models.CharField(max_length=20)),
                ('password', models.CharField(max_length=20)),
                ('balance', models.IntegerField()),
                ('admin', models.BooleanField()),
                ('some', models.BooleanField()),
            ],
        ),
    ]
