# Generated by Django 5.2.11 on 2026-03-15 17:42

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('tickets', '0001_initial'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='user',
            name='some',
        ),
    ]
