# Generated by Django 5.2.11 on 2026-03-15 17:44

from django.db import migrations

def populate(apps, schema_editor):
    User = apps.get_model("tickets", "User")
    u = User(username = "esim", password = "1234", balance = 200, admin = False)
    u.save()
    a = User(username = "admin", password = "admin", balance = 0, admin = True)
    a.save()

class Migration(migrations.Migration):

    dependencies = [
        ('tickets', '0002_remove_user_some'),
    ]

    operations = [
        migrations.RunPython(populate)
    ]
