# Generated by Django 5.2.11 on 2026-03-23 08:59

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('tickets', '0003_auto_20260315_1744'),
    ]

    operations = [
        migrations.CreateModel(
            name='Event',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField()),
                ('price', models.IntegerField()),
                ('transactionfee', models.FloatField(verbose_name=2.5)),
                ('extrafee', models.FloatField(verbose_name=5.0)),
                ('extrafee2', models.FloatField(verbose_name=4.5)),
                ('extrafee3', models.FloatField(verbose_name=150)),
                ('extrafee4', models.FloatField(verbose_name=0.5)),
            ],
        ),
    ]
