# Generated by Django 5.2.11 on 2026-03-23 10:07

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('tickets', '0004_event'),
    ]

    operations = [
        migrations.AlterField(
            model_name='event',
            name='extrafee',
            field=models.FloatField(db_default=5.0),
        ),
        migrations.AlterField(
            model_name='event',
            name='extrafee2',
            field=models.FloatField(db_default=4.5),
        ),
        migrations.AlterField(
            model_name='event',
            name='extrafee3',
            field=models.FloatField(db_default=150),
        ),
        migrations.AlterField(
            model_name='event',
            name='extrafee4',
            field=models.FloatField(db_default=0.5),
        ),
        migrations.AlterField(
            model_name='event',
            name='transactionfee',
            field=models.FloatField(db_default=2.5),
        ),
    ]
