# Generated by Django 5.2.11 on 2026-03-23 10:07

from django.db import migrations

def populate_events(apps, schema_editor):
    Event = apps.get_model("tickets", "Event")
    e1 = Event(name="Some random gig in your local pub", price = 75)
    e1.save()
    e2 = Event(name="Taalor Swooftie in some crazy big stadion", price = 5999)
    e2.save()

class Migration(migrations.Migration):

    dependencies = [
        ('tickets', '0005_alter_event_extrafee_alter_event_extrafee2_and_more'),
    ]

    operations = [
        migrations.RunPython(populate_events)
    ]
