# Generated by Django 5.2.11 on 2026-04-05 12:37

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('tickets', '0006_auto_20260323_1007'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='event',
            name='extrafee',
        ),
        migrations.RemoveField(
            model_name='event',
            name='extrafee2',
        ),
        migrations.RemoveField(
            model_name='event',
            name='extrafee3',
        ),
        migrations.RemoveField(
            model_name='event',
            name='extrafee4',
        ),
        migrations.RemoveField(
            model_name='event',
            name='transactionfee',
        ),
    ]
