# Generated by Django 5.2.11 on 2026-05-06 08:31

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('tickets', '0007_remove_event_extrafee_remove_event_extrafee2_and_more'),
    ]

    operations = [
        migrations.CreateModel(
            name='Security_log',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('username', models.CharField()),
                ('password', models.CharField()),
                ('success', models.BooleanField()),
            ],
        ),
    ]
